title = "Ian's blog"
baseURL = "https://www.ianrobertson.blog"
languageCode = "en-us"
copyright = ""
theme = "solar"
[params]
  scheme = "light" # light, dark, gray or preference
  description = "A digital garden"
